---
title: "Fires Amazon 2020-2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(tibbletime)
library(viridis)
library(dplyr)
library(lubridate)
library(ggplot2)
library(raster)
library(sf)
library(plotly)

####
####
####

#working directory
wd =  "/Users/Hailey Viera/Documents/Summer_2021_Brando_Research"

####
####
####

#2019
#fires_e_2019 = st_read(file.path(wd, "Neils/Fire_events_by_type/2019/Fire_events_by_type.shp"))
#fires_d_2019 = st_read(file.path(wd, "Neils/Fire_detection_by_type/2019/Fire_detections_by_type.shp"))

####
####
####

#2020
fires_20 <- st_read(file.path(wd, "/Drive_DashData_2020/fire_atlas_events_20200817.shp"))
#2021
fires_21 <- st_read(file.path(wd, "/Drive_DashData_2021/fire_atlas_events_20210711.shp"))

#Weekly August-September 2021
fires_21_0815 <- st_read(file.path(wd, "/Weekly_Data/W8_15_2021/fire_atlas_events_20210815.shp"))

fires_21_0822 <- st_read(file.path(wd, "/Weekly_Data/W8_22_2021/fire_atlas_events_20210822.shp"))

fires_21_0829 <- st_read(file.path(wd, "/Weekly_Data/W8_29_2021/fire_atlas_events_20210829.shp"))

fires_21_0904 <- st_read(file.path(wd, "/Weekly_Data/W9_04_2021/fire_atlas_events_20210904.shp"))

fires_21_0912 <- st_read(file.path(wd, "/Weekly_Data/W9_12_2021/fire_atlas_events_20210912.shp"))

#fires_21_0815= fires_21_0815 %>% 
#  rename(start_DOY=start_date,
#         last_DOY=last_date)

#fires_d <- st_read(file.path(wd, "Neils/Fire_detection_by_type/2020/fire_atlas_viirs_detections_20200817.shp"))

#Variable for current fires (current week)
fires <- fires_20 %>%
  bind_rows(fires_20, fires_21_0912)
  
#Variable for previous week
fires_prev <- fires_20 %>%
  bind_rows(fires_20, fires_21_0904)
  
####
####
####

#Shapefiles Brazil
brazil_s <- st_read(file.path(wd, "Shapefiles/Bramzstates_polyline.shp"))
abasin <- st_read(file.path(wd, "Shapefiles/panamazonpoly.shp"))

```

```{r}
#states <- fires_e[brazil_s, ]
#amazon <- fires_e[abasin, ]

aa <- fires %>%  
  filter(biome == 1) %>%
  
  mutate(
    Fire = case_when(
      fire_type == 1 ~ "savanna and grassland",
      fire_type == 2 ~ "small clearing and agriculture",
      fire_type == 3 ~ "understory",
      fire_type == 4 ~ "deforestation"
  ),
  start_date = ymd(start_date),
  last_date = ymd(last_date),
  Year = year(start_date),
  Year = ifelse(is.na(Year), 2021, Year)
  )
```

```{r}
#Current 2021 variables:
aa_2021 <- fires_21_0912 %>%  
  filter(biome == 1) %>%
  
  mutate(
    Fire = case_when(
      fire_type == 1 ~ "savanna and grassland",
      fire_type == 2 ~ "small clearing and agriculture",
      fire_type == 3 ~ "understory",
      fire_type == 4 ~ "deforestation"
  ),
  start_date = ymd(start_date),
  last_date = ymd(last_date),
  Year = year(start_date),
  Year = ifelse(is.na(Year), 2021, Year)
  )

calc_fire_event_2021 <- 
  as_tibble(aa_prev) %>% 
  #rename(start_date = start_DOY) %>%
  filter(start_DOY >= 1, is_active == 1) %>%
  group_by(start_DOY, Fire, Year) %>%
  summarise(active_fires = sum(fire_count, na.rm=T)) %>% 
  group_by(Fire, Year) %>%
  mutate(mov_avg = rolling_mean(active_fires))  %>%
  ungroup()

```

```{r}

fig1_Wk5 <- 
  ggplot(data = aa)+
  geom_sf(data = abasin, fill = NA) +
  geom_sf(data = brazil_s, fill = NA, color = "gray") +
  geom_sf(aes(fill = start_DOY, color = start_DOY), alpha = .2) +
  scale_fill_viridis(option = "magma") +
  scale_color_viridis(option = "magma") +
  facet_wrap(~Year) +
  theme_minimal()

print(fig1_Wk5)
```

```{r}

rolling_mean <- rollify(mean, window = 7)

calc_fire_event <- 
  as_tibble(aa) %>% 
  #rename(start_date = start_DOY) %>%
  filter(start_DOY >= 1, is_active == 1) %>%
  group_by(start_DOY, Fire, Year) %>%
  summarise(active_fires = sum(fire_count, na.rm=T)) %>% 
  group_by(Fire, Year) %>%
  mutate(mov_avg = rolling_mean(active_fires))  %>%
  ungroup()
```


```{r}
#Current week's figure(s)
fig2_Wk5 <- calc_fire_event %>%
  ggplot() +
  geom_area(aes(x = start_DOY, 
             y = active_fires, 
             fill = Fire), alpha = 0.8) +
  #scale_fill_viridis(discrete = TRUE, option="E") +
  scale_fill_manual(values = c("darkred", "orange", "black", "springgreen4")) +
  labs(title = "Amazon fires") +
  ylab("Active fire counts") +
  xlab("Date") +
  #scale_x_date(date_labels = "%b %d", date_breaks = "7 days")+
  theme_minimal() +
  facet_wrap(~Year) +
  theme(legend.position = c(0.2, 0.4)) 
  
ggplotly(fig2_Wk5)

print(fig2_Wk5)

```

```{r}
#Current (2021) active fire count separated by type of fire
fig2b_Wk5 <- calc_fire_event %>%
  ggplot() +
  #filter(Year == 2021) +
  geom_area(aes(x = start_DOY, 
             y = active_fires, 
             fill = Fire), alpha = 0.8) +
  #scale_fill_viridis(discrete = TRUE, option="E") +
  scale_fill_manual(values = c("darkred", "orange", "black", "springgreen4")) +
  labs(title = "Amazon fires") +
  ylab("Total active fire counts") +
  xlab("Date") +
  #scale_x_date(date_labels = "%b %d", date_breaks = "7 days")+
  theme_minimal() +
  #facet_wrap(~Year) +
  facet_wrap(~Fire, scales = "free_y") +
  theme(legend.position = c(0.2, 0.4)) 
  
ggplotly(fig2b_Wk5)

print(fig2b_Wk5)
```

```{r}
#Previous weeks' figure 2, and interactive ggplot
fig2_prev <- calc_fire_event_prev %>%
  ggplot() +
  geom_area(aes(x = start_DOY, 
             y = active_fires, 
             fill = Fire), alpha = 0.8) +
  #scale_fill_viridis(discrete = TRUE, option="E") +
  scale_fill_manual(values = c("darkred", "orange", "black", "springgreen4")) +
  labs(title = "Amazon fires") +
  ylab("Active fire counts") +
  xlab("Date") +
  #scale_x_date(date_labels = "%b %d", date_breaks = "7 days")+
  theme_minimal() +
  facet_wrap(~Year) +
  theme(legend.position = c(0.2, 0.4)) 
  
ggplotly(fig2_prev)
```

```{r}

fig3_wk5 <- calc_fire_event %>%
  ggplot() +
  geom_area(aes(x = start_DOY, 
             y = mov_avg, 
             fill = Fire), alpha = 0.8) +
  #scale_fill_viridis(discrete = TRUE, option="E") +
  scale_fill_manual(values = c("darkred", "orange", "black", "springgreen4")) +
  labs(title = "Amazon fires (7-day moving average)") +
  ylab("Active fire counts") +
  xlab("Date") +
#  scale_x_date(date_labels = "%b %d", date_breaks = "7 days")+
  theme_minimal() +
  facet_wrap(~Year) +
  theme(legend.position = c(0.2, 0.4)) 
  
ggplotly(fig3_wk5)

print(fig3_wk5)
```


```{r}
fig4_wk5 <- calc_fire_event %>%
  #filter(start_date >= ymd("2020-07-01")) %>%
  ggplot() +
  geom_col(aes(x = start_DOY, 
               y = active_fires,
               #color = Fire,
               fill = Fire), position = "dodge", color = NA, alpha = .3) +
  geom_line(aes(x = start_DOY, 
             y = mov_avg,
             color = Fire), lwd = 1.25) +
  #scale_fill_viridis(discrete = TRUE, option="E") +
  #scale_fill_manual(values = c("orange", "blue", "darkgreen", "darkred"))+
  #scale_x_date(date_labels = "%b %d", date_breaks = "7 days")+
  scale_fill_manual(values = c("darkred", "orange", "black", "springgreen4")) +
  scale_color_manual(values = c("darkred", "orange", "black", "springgreen4")) +
  labs(title = "Amazon fires (7-day moving average)") +
  ylab("Active fire counts") +
  xlab("Date") +
  facet_grid(Year~Fire) +
  theme_minimal() +
  theme(legend.position = "none") 

ggplotly(fig4_wk5)

print(fig4_wk5)
```

```{r}
fig4b_wk5 <- calc_fire_event %>%
  #filter(start_date >= ymd("2020-07-01")) %>%
  ggplot() +
  #geom_col(aes(x = start_DOY, 
  #             y = active_fires,
  #             #color = Fire,
  #             fill = Fire), position = "dodge", color = NA, alpha = .3) +
  #geom_line(aes(x = start_DOY, 
  #           y = mov_avg,
  #           linetype = as.factor(Year),
  #           color = Fire), lwd = 0.55) +
    geom_point(aes(x = start_DOY, 
             y = mov_avg,
             shape = as.factor(Year),
             color = as.factor(Year)), size = 0.4) +

  #scale_fill_viridis(discrete = TRUE, option="E") +
  #scale_fill_manual(values = c("orange", "blue", "darkgreen", "darkred"))+
  #scale_x_date(date_labels = "%b %d", date_breaks = "7 days")+
  #scale_fill_manual(values = c("darkred", "orange", "black", "springgreen4")) +
  #scale_color_manual(values = c("darkred", "orange", "black", "springgreen4")) +
  labs(title = "Amazon fires (7-day moving average)") +
  ylab("Active fire counts") +
  xlab("Date") +
  facet_wrap(~Fire) +
  theme_minimal() +
  theme(legend.position = "none") 

ggplotly(fig4b_wk5)

print(fig4b_wk5)
```


```{r}
library(tidyr)
library(kableExtra)
library(formattable)

rr = as_tibble(aa) %>% 
  filter(start_DOY >= 182, is_active == 1) %>%
  group_by(start_DOY, Fire) %>%
  summarise(active_fires = sum(fire_count, na.rm=T)) %>% 
  group_by(Fire) %>%
  mutate(mov_avg = rolling_mean(active_fires)) %>%
  filter(start_DOY %in% c(max(start_DOY), max(start_DOY)-14)) %>%
  arrange(Fire, start_DOY) %>%
  mutate(Date = start_DOY,
         mov_avg = round(mov_avg)) %>%
  dplyr::select(-active_fires, -start_date) %>%
  pivot_wider(names_from = Date, values_from = mov_avg) %>%
  ungroup()

names(rr) = c("Fire", "Two weeks ago", "This week")

rr <- rr %>% 
  tibble::add_row(Fire = "Total",
                  `Two weeks ago` = sum(rr$`Two weeks ago`),
                  `This week` = sum(rr$`This week`))

rr$Perc_change = round(((rr$`This week` - rr$`Two weeks ago`) / rr$`Two weeks ago`)*100, 0)

#rr$Perc_change = color_tile("white", "orange")(rr$Perc_change)

rr$Perc_change <- ifelse(
  rr$Perc_change > 0,
  cell_spec(rr$Perc_change, color = "darkred", bold = T),
  cell_spec(rr$Perc_change, color = "darkblue", bold = F)
)



kbl(rr, escape = F) %>%
  kable_styling("hover", full_width = F) %>%
  row_spec(5, bold = T, color = "white", background = "grey")


```


```{r}

fig5_wk5<- as_tibble(aa) %>% 
  filter(is_active == 1,
         start_date >= ymd("2021-05-01")) %>%
  group_by(start_date, Fire) %>%
  summarise(frp = mean(frp, na.rm=TRUE)) %>% 
  group_by(Fire) %>%
  mutate(mov_avg = rolling_mean(frp)) %>%
  ggplot() +
  geom_line(aes(x = start_date,
                color = Fire,
             y = mov_avg)) +
  geom_col(aes(x = start_date,
               fill = Fire,
               y = frp), position = "dodge", alpha = .3) +
  scale_x_date(date_labels = "%b %d", date_breaks = "15 days")+
  scale_fill_manual(values = c("darkred", "orange", "black", "springgreen4")) +
  scale_color_manual(values = c("darkred", "orange", "black", "springgreen4")) +
  labs(title = "Fire radiative power of Amazon fires (7-day moving average)") +
  ylab("FRP") +
  xlab("Date") +
  facet_wrap(~Fire) +
  theme_minimal() +
  theme(legend.position = "none") 

ggplotly(fig5_wk5)

print(fig5_wk5)
```

```{r}
#Figure for displaying/comparing the number of fires inside and outside the Amazon biome.
#Data separated by whether or not it is in the Amazon biome (similar to the aa variable)
bb <- fires_21_0822 %>%  
  mutate(
    Amazon = case_when(
      biome == 1 ~ "inside"
      biome == 0 ~ "outside"
  ),
  start_date = start_DOY == 1,
  last_date = last_DOY,
  Year = 2021,
  #Year = ifelse(is.na(Year), 2021, Year)
  )
  
calc_fire_biome <- 
  as_tibble(bb) %>% 
  #rename(start_date = start_DOY) %>%
  filter(start_DOY >= 1, is_active == 1) %>%
  group_by(start_DOY, Amazon, Year) %>%
  #summarise(active_fires = sum(fire_count, na.rm=T)) %>% 
  #group_by(Fire, Year) %>%
  mutate(mov_avg = rolling_mean(active_fires))  %>%
  ungroup()
  
#fig6_wk2 <- 
```
```{r}
library(rgdal)
#Figure for displaying/comparing the different areas/states and the number of fires in each.
#Brazil cropped area
#Use the raster format file, the .shp file
fires_raster <- readOGR(file.path(wd, "/Weekly_Data/W8_29_2021/fire_atlas_events_20210829.shp"))

brazil_crop <- crop(x = fires_raster, y = brazil_s)

```
